#!/bin/bash
set -e

cd "$(dirname "$0")/.."

NUM=${1:-3}
CONTRACT_DIR="$(cd ../smartContract && pwd)"
ENV_FILE="$CONTRACT_DIR/.env"
ENV_DIR="./env"

echo "=== Community Storage Setup ($NUM servers) ==="
echo ""

# 1. Register providers on blockchain
echo "[1/4] Registering providers..."
cd "$CONTRACT_DIR"
NUM_PROVIDERS=$NUM npm run setup --silent
cd - > /dev/null

# Load env vars from smartContract/.env
set -a; source "$ENV_FILE" 2>/dev/null || true; set +a

# Default contract address if not set
STORAGE_REGISTRY_ADDRESS="${STORAGE_REGISTRY_ADDRESS:-AS14XRdSCc87DZbMx2Zwa1BWK2R8WmwShFGnTtVa2RLDYyx2vwyn}"

# 2. Generate individual .env files for each container (keeps private keys out of docker-compose.yml)
echo ""
echo "[2/4] Generating environment files..."

mkdir -p "$ENV_DIR"

for i in $(seq 1 $NUM); do
  ADDR_VAR="PROVIDER_${i}_ADDRESS"
  SECRET_VAR="PROVIDER_${i}_PRIVATE_KEY"
  PUBLIC_PORT=$((4342+i))

  cat > "$ENV_DIR/storage-$i.env" << EOF
MASSA_ADDRESS=${!ADDR_VAR:-}
STORAGE_LIMIT_GB=${STORAGE_LIMIT_GB:-1}
RUST_LOG=info
CONTRACT_ADDRESS=${STORAGE_REGISTRY_ADDRESS:-}
STORAGE_REGISTRY_ADDRESS=${STORAGE_REGISTRY_ADDRESS:-}
MASSA_JSON_RPC=${MASSA_RPC_URL:-https://buildnet.massa.net/api/v2}
MASSA_RPC_URL=${MASSA_RPC_URL:-https://buildnet.massa.net/api/v2}
MASSA_GRPC_URL=${MASSA_GRPC_URL:-grpc://buildnet.massa.net:33037}
PRIVATE_KEY=${!SECRET_VAR:-}
PUBLIC_ENDPOINT=http://localhost:$PUBLIC_PORT
EOF
  echo "  Created $ENV_DIR/storage-$i.env"
done

# Ensure env directory is gitignored
if ! grep -q "^env/$" .gitignore 2>/dev/null; then
  echo "env/" >> .gitignore
  echo "  Added env/ to .gitignore"
fi

# 3. Generate docker-compose.yml (NO private keys - uses env_file)
echo ""
echo "[3/4] Starting servers..."

cat > docker-compose.yml << 'EOF'
# Generated by setup.sh - DO NOT COMMIT PRIVATE KEYS
# Private keys are stored in env/*.env files (gitignored)
services:
EOF

for i in $(seq 1 $NUM); do
  PUBLIC_PORT=$((4342+i))
  P2P_PORT=$((4000+i))

  cat >> docker-compose.yml << EOF
  storage-$i:
    build: .
    container_name: storage-$i
    ports: ["$PUBLIC_PORT:4343", "$P2P_PORT:4001/tcp", "$P2P_PORT:4001/udp"]
    env_file: ./env/storage-$i.env
    volumes: [storage-$i-data:/app/data]
    healthcheck: {test: ["CMD", "curl", "-f", "http://localhost:4343/health"], interval: 10s, timeout: 3s, retries: 3}
EOF
done

# Volumes
echo "volumes:" >> docker-compose.yml
for i in $(seq 1 $NUM); do echo "  storage-$i-data:" >> docker-compose.yml; done

# Start
docker compose up -d --build 2>&1 | grep -v "pull" || true

# Wait for health
echo -n "Health check"
for _ in $(seq 1 30); do
  HEALTHY=$(docker compose ps 2>/dev/null | grep -c "(healthy)" || echo 0)
  [ "$HEALTHY" -ge "$NUM" ] && break
  sleep 1; echo -n "."
done
echo ""

# Status
echo ""
docker compose ps --format "table {{.Name}}\t{{.Status}}" 2>/dev/null

# 4. P2P address registration happens automatically in Rust server
echo ""
echo "[4/4] Waiting for P2P registration..."
sleep 5

# Show P2P connectivity status
echo ""
echo "=== P2P Connectivity Status ==="
echo ""

for i in $(seq 1 $NUM); do
  PORT=$((4342+i))
  echo "storage-$i (port $PORT):"

  PEERS_JSON=$(curl -s "http://localhost:$PORT/peers" 2>/dev/null || echo "{}")

  PEER_ID=$(echo "$PEERS_JSON" | grep -o '"local_peer_id":"[^"]*"' | cut -d'"' -f4)
  CONNECTED=$(echo "$PEERS_JSON" | grep -o '"connected_peers":\[[^]]*\]' | grep -o '"[^"]*"' | grep -v connected_peers | wc -l | tr -d ' ')

  if [ -n "$PEER_ID" ]; then
    echo "  Peer ID: ${PEER_ID:0:20}..."
    echo "  Connected peers: $CONNECTED"
  else
    echo "  Not ready yet"
  fi
done

echo ""
echo "=== Done ==="
echo ""
echo "Endpoints:"
for i in $(seq 1 $NUM); do
  echo "  storage-$i: http://localhost:$((4342+i))"
done
echo ""
echo "Commands:"
echo "  View logs:    docker compose logs -f"
echo "  P2P status:   curl http://localhost:4343/peers"
echo "  Stop:         ./scripts/teardown.sh"
